CC = gcc
CFLAGS = -Werror -Wall -I /nix/store/n15bxkd7id2gvlwpihm4kp675aqkrwmj-glibc-2.40-36-dev/include

run:
	./a.out

wait:
	$(CC) homework_wait.c 

fork:
	$(CC) homework_fork.c

thread:
	$(CC) homework_thread.c

semaphore:
	$(CC) homework_semaphore.c
